# _config.yml
name: Syed Ejlal Shah
bio: High School Graduate. Second Year of computing in University.
social_media:
  - github: https://ejlalshah.github.io
  - linkedin: www.linkedin.com/in/syed-ejlal-shah-964454258